# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Tinyfox
tagline:          'A hust campus network supplicant on linux'
description:      'A hust campus network supplicant on linux'
url:              https://dreamanddead.github.io
baseurl:          /tinyfox

author:
  name:           'DreamAndDead'
  url:            https://dreamanddead.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/DreamAndDead/tinyfox

# Gem
gems:             [jekyll-paginate, jekyll-gist]
